// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css'; // Assuming you have global styles
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout2({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <Navbar /> {/* Include the Navbar component here */}
        <main>{children}</main>{/*  This is where page.tsx content will be rendered */}
      
    </>
  );
}

